trigger:
  branches:
    include:
      - main

pool:
  name: Self_Hosted

steps:
  - script: |
      python3 --version
      python3 -m pip install --upgrade pip
      pip3 install pygame
    displayName: 'Use system Python & install dependencies'

  - script: |
      echo "Running the game..."
      python3 main.py
    displayName: 'Run Tetris Game'
